/**
 * Portfolio Performance PDF Generator
 * 
 * Generates Kwanti-style PDF reports for portfolio performance metrics.
 */

import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { MultiPortfolioResult, PeriodMetrics } from './portfolio-metrics'
import { sortPortfolioNames } from './portfolio-order'

// Extend jsPDF type to include autoTable
declare module 'jspdf' {
  interface jsPDF {
    lastAutoTable: { finalY: number }
  }
}

/**
 * Format percentage value for display
 */
function formatPct(value: number | null, decimals: number = 1): string {
  if (value === null || value === undefined) return '-'
  return `${(value * 100).toFixed(decimals)}%`
}

/**
 * Format numeric value for display
 */
function formatNum(value: number | null, decimals: number = 2): string {
  if (value === null || value === undefined) return '-'
  return value.toFixed(decimals)
}

/**
 * Important Disclosures text for PDF reports
 */
const IMPORTANT_DISCLOSURES = `IMPORTANT DISCLOSURES

This report is being provided by your financial professional as a courtesy and is not intended to be used as or in lieu of an account statement.

This report presents past performance, which does not guarantee future results. The investment return and principal value will fluctuate thus an investor's shares, when redeemed, may be worth more or less than their original cost. Current performance may be higher or lower than return data quoted herein.

The portfolio performance presented in this report is hypothetical and based on simulated investments. Unlike the results shown in an actual performance record, these results do not represent actual trading. Also, because these trades have not actually been executed, these results may have under-or over-compensated for the impact, if any, of certain market factors, such as lack of liquidity. Simulated or hypothetical trading programs in general are also subject to the fact that they are designed with the benefit of hindsight. No representation is being made that any account will or is likely to achieve profits or losses similar to these being shown.

Returns in this report are time-weighted returns (TWR). Returns include distribution income such as dividends. The simulation of model portfolios does not take into account trading costs and tax implications.

The projections or other information generated by Kwanti Analytics regarding the likelihood of various investment outcomes are hypothetical in nature, do not reflect actual investment results and are not guarantees of future results.

Performance is presented net of advisory fees. Other fees borne by investors and not included in this report are: commissions, custodial charges and sales loads. If applicable, these fees will have a compounding effect on performance that can be material.

Clockwise Capital, which is a registered investment advisor. Information presented herein is for educational purposes only and does not intend to make an offer or solicitation for the sale or purchase of any specific securities, investments, or investment strategies. Investments involve risk and unless otherwise stated, are not guaranteed. Readers of the information contained on this handout should be aware that any action taken by the viewer/reader based on this information is taken at their own risk. This information does not address individual situations and should not be construed or viewed as any type of individual or group recommendation. Be sure to first consult with a qualified financial adviser, tax professional, and/or legal counsel before implementing any securities, investments, or investment strategies discussed. Any performance shown by Clockwise Capital for the relevant time periods is based upon composite results of multiple Guttridge Capital Management portfolios and Clockwise Capital portfolios. Portfolio performance is the result of the application of the Clockwise Capital and Guttridge Capital Management's investment process. The composite includes the All Stock Portfolio managed by Guttridge Capital Management (2014-2016), the separately managed accounts (SMA) (2017-2021) managed by Clockwise Capital, and the model portfolios (Models) (2022-2025) managed by Clockwise Capital. Portfolio performance is not shown net of the advisory fees as different Independent Advisors using Clockwise Models possess different fees and sample trading costs are based on Clockwise Capital's Custodians, which are Charles Schwab, Betterment LLC and Altruist. Performance does not reflect the deduction of other fees or expenses, including but not limited to brokerage fees, custodial fees and fees and expenses charged by mutual funds and other investment companies. Performance results shown include the reinvestment of dividends and interest on cash balances where applicable. The data used to calculate the portfolio performance was obtained from sources deemed reliable and then organized and presented by Clockwise Capital. The performance calculations have not been audited by any third party. Actual performance of client portfolios may differ materially due to the timing related to additional client deposits or withdrawals and the actual deployment and investment of a client portfolio, the length of time various positions are held, the client's objectives and restrictions, and fees and expenses incurred by any specific individual portfolio.

Benchmarks: Performance results shown are compared to the performance of the S&P 500 Index without dividends reinvested. The index results do not reflect fees and expenses and you typically cannot invest in an index.

Return Comparison: The S&P 500 was chosen for comparison as it is generally well recognized as an indicator or representation of the stock market in general and includes a cross section of equity holdings. PAST PERFORMANCE IS NO GUARANTEE OF FUTURE RESULTS.

INDEXES AND BENCHMARKS
References to indexes and benchmarks are hypothetical illustrations of aggregate returns and do not reflect the performance of any actual investment. Investors cannot invest in an index.

S&P 500 Index TR: Measures the performance of 500 widely held, large-capitalization US stocks.
Bloomberg US Aggregate Bond Index: Measures the U.S. bond market and covers all major types of bonds, including taxable corporate bonds, treasury bonds, and municipal bonds.
S&P 500 Index Price: Measures the performance of 500 widely held, large-capitalization US stocks.

DEFINITIONS

Alpha: the excess return of the investment over the benchmark, after adjusting for risk. A positive value implies that the investment has performed better than expected, relatively to its risk. The benchmark used for alpha calculation in this report is the S&P500 Index Total Return.

Beta: the volatility of the investment compared to the volatility of the benchmark. A value lower than 1 indicates that the investment is less volatile than the benchmark. A value greater than 1 indicates a higher volatility. The benchmark used for beta calculation in this report is the S&P500 Index Total Return.

Fund expense ratio: for investment funds, the expense ratio as reported in the fund's prospectus.

Maximum drawdown: the largest percent retrenchment from an investment's peak value to the investment's valley value for a given period.

Risk (Standard Deviation): a measure of dispersion of returns around their historical average. The higher the standard deviation, the more widely the investment's returns vary over time.

Sharpe ratio: compares the investment return against the risk-free return (US Treasury Bill), after adjusting for risk. The greater the Sharpe ratio, the better its risk-adjusted performance.

Up/Down capture ratio: shows what portion of a market performance was captured by an investment in up and down markets.

Yield 12-month: the sum of distributions from the asset(s) over 12 trailing months, divided by the current market price of the asset(s).

Yield SEC: the annualized yield based on the 30-day period ending on the last day of previous month.

The information and analysis contained herein does not constitute investment advice offered by Kwanti and Morningstar, and is not warranted to be correct, complete or accurate. Kwanti and Morningstar are not responsible for any damages or losses arising from use of this information and analysis. Asset allocation data ©2024 Morningstar. All rights reserved. The asset allocation data contained herein is proprietary to Morningstar and/or its content providers.

These results are hypothetical. The performance data quoted represents past performance. Past performance does not guarantee future results. Investment return and principal value will fluctuate so that an investor's shares, when redeemed, may be worth more or less than their original cost.`

/**
 * Add disclosure pages to PDF document
 */
function addDisclosurePages(doc: jsPDF): void {
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 15
  const lineHeight = 4
  const maxWidth = pageWidth - (margin * 2)
  
  // Add new page for disclosures
  doc.addPage()
  
  let yPos = 20
  
  // Title
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(0, 0, 0)
  doc.text('IMPORTANT DISCLOSURES', margin, yPos)
  
  yPos += 10
  
  // Set disclosure text style
  doc.setFontSize(7)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(60, 60, 60)
  
  // Split disclosure into paragraphs
  const paragraphs = IMPORTANT_DISCLOSURES.split('\n\n')
  
  for (const paragraph of paragraphs) {
    // Skip the title as we already added it
    if (paragraph === 'IMPORTANT DISCLOSURES') continue
    
    // Check if this is a section header (all caps or starts with caps followed by colon)
    const isHeader = /^[A-Z][A-Z\s&\/]+(:)?$/.test(paragraph.trim()) || 
                     paragraph.startsWith('INDEXES AND BENCHMARKS') ||
                     paragraph.startsWith('DEFINITIONS') ||
                     paragraph.startsWith('Benchmarks:') ||
                     paragraph.startsWith('Return Comparison:')
    
    if (isHeader) {
      yPos += 3
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(8)
    } else {
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(7)
    }
    
    // Split text to fit within page width
    const lines = doc.splitTextToSize(paragraph, maxWidth)
    
    // Check if we need a new page
    const textHeight = lines.length * lineHeight
    if (yPos + textHeight > pageHeight - 20) {
      doc.addPage()
      yPos = 20
    }
    
    // Add lines
    for (const line of lines) {
      doc.text(line, margin, yPos)
      yPos += lineHeight
    }
    
    // Add spacing between paragraphs
    yPos += 2
  }
  
  // Footer on disclosure page
  const footerY = pageHeight - 10
  doc.setFontSize(8)
  doc.setTextColor(150, 150, 150)
  doc.text('Clockwise Capital - Disclosures', margin, footerY)
}

/**
 * Generate PDF for a single portfolio (Kwanti-style)
 */
export function generatePortfolioPDF(
  data: MultiPortfolioResult,
  portfolioName: string
): jsPDF {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  })
  
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 15
  let yPos = 20
  
  const portfolioResult = data.portfolios[portfolioName]
  if (!portfolioResult) {
    doc.text('Portfolio not found', margin, yPos)
    return doc
  }
  
  const periods = portfolioResult.periods
  const periodNames = periods.map(p => p.periodName)
  
  // Header
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text('Performance', margin, yPos)
  
  yPos += 8
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 100, 100)
  doc.text(`As of ${data.asOfDate}`, margin, yPos)
  
  yPos += 3
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, margin, yPos)
  
  // Portfolio name
  yPos += 10
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(0, 0, 0)
  doc.text(portfolioName, margin, yPos)
  
  // Periodic Returns Section
  yPos += 12
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('Periodic Returns', margin, yPos)
  
  yPos += 5
  
  // Returns table
  const returnsData = [
    [
      { content: portfolioName, styles: { fontStyle: 'bold' as const } },
      ...periods.map(p => formatPct(p.portfolioReturn, 2))
    ],
    [
      { content: '$SPX', styles: { textColor: [150, 100, 50] as [number, number, number] } },
      ...periods.map(p => formatPct(p.benchmarkReturn, 2))
    ]
  ]
  
  autoTable(doc, {
    startY: yPos,
    head: [['', ...periodNames]],
    body: returnsData as unknown as (string | object)[][],
    theme: 'plain',
    styles: {
      fontSize: 9,
      cellPadding: 2
    },
    headStyles: {
      fillColor: [245, 245, 245],
      textColor: [100, 100, 100],
      fontStyle: 'bold'
    },
    columnStyles: {
      0: { cellWidth: 50 }
    },
    margin: { left: margin, right: margin }
  })
  
  yPos = doc.lastAutoTable.finalY + 10
  
  // Risk Metrics Section
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('Risk Metrics', margin, yPos)
  
  yPos += 5
  
  // Define metrics configuration
  const metricsConfig: Array<{
    label: string
    portfolioKey: keyof PeriodMetrics
    benchmarkKey: keyof PeriodMetrics
    formatter: (v: number | null) => string
  }> = [
    { label: 'Risk (standard deviation)', portfolioKey: 'portfolioStdDev', benchmarkKey: 'benchmarkStdDev', formatter: (v) => formatPct(v, 1) },
    { label: 'Alpha', portfolioKey: 'portfolioAlpha', benchmarkKey: 'benchmarkAlpha', formatter: (v) => formatPct(v, 1) },
    { label: 'Beta', portfolioKey: 'portfolioBeta', benchmarkKey: 'benchmarkBeta', formatter: (v) => formatNum(v, 2) },
    { label: 'Sharpe ratio', portfolioKey: 'portfolioSharpeRatio', benchmarkKey: 'benchmarkSharpeRatio', formatter: (v) => formatNum(v, 2) },
    { label: 'Maximum drawdown', portfolioKey: 'portfolioMaxDrawdown', benchmarkKey: 'benchmarkMaxDrawdown', formatter: (v) => formatPct(v, 1) },
    { label: 'Up capture ratio', portfolioKey: 'portfolioUpCapture', benchmarkKey: 'benchmarkUpCapture', formatter: (v) => formatNum(v, 2) },
    { label: 'Down capture ratio', portfolioKey: 'portfolioDownCapture', benchmarkKey: 'benchmarkDownCapture', formatter: (v) => formatNum(v, 2) }
  ]
  
  // Build risk metrics table data
  const riskMetricsData: (string | object)[][] = []
  
  for (const metric of metricsConfig) {
    // Metric label row
    riskMetricsData.push([
      { content: metric.label, styles: { fontStyle: 'bold' as const, fillColor: [250, 250, 250] as [number, number, number] } },
      ...periodNames.map(() => ({ content: '', styles: { fillColor: [250, 250, 250] as [number, number, number] } }))
    ])
    
    // Portfolio value row
    riskMetricsData.push([
      `  ${portfolioName}`,
      ...periods.map(p => metric.formatter(p[metric.portfolioKey] as number | null))
    ])
    
    // Benchmark value row
    riskMetricsData.push([
      { content: '  $SPX', styles: { textColor: [150, 100, 50] as [number, number, number] } },
      ...periods.map(p => metric.formatter(p[metric.benchmarkKey] as number | null))
    ])
  }
  
  autoTable(doc, {
    startY: yPos,
    head: [['', ...periodNames]],
    body: riskMetricsData as unknown as (string | object)[][],
    theme: 'plain',
    styles: {
      fontSize: 9,
      cellPadding: 2
    },
    headStyles: {
      fillColor: [245, 245, 245],
      textColor: [100, 100, 100],
      fontStyle: 'bold'
    },
    columnStyles: {
      0: { cellWidth: 50 }
    },
    margin: { left: margin, right: margin }
  })
  
  yPos = doc.lastAutoTable.finalY + 10
  
  // 3Y Cumulative Section (if available) - with benchmark comparison
  if (portfolioResult.cumulative3Y) {
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text('3-Year Cumulative Performance', margin, yPos)
    
    yPos += 5
    
    const cum3YData = [
      ['', portfolioName, 'S&P 500 TR'],
      ['Return', formatPct(portfolioResult.cumulative3Y.portfolioReturn, 2), formatPct(portfolioResult.cumulative3Y.benchmarkReturn, 2)],
      ['Std Dev', formatPct(portfolioResult.cumulative3Y.portfolioStdDev, 1), formatPct(portfolioResult.cumulative3Y.benchmarkStdDev, 1)],
      ['Alpha', formatPct(portfolioResult.cumulative3Y.portfolioAlpha, 1), '0.0%'],
      ['Beta', formatNum(portfolioResult.cumulative3Y.portfolioBeta), '1.00'],
      ['Sharpe Ratio', formatNum(portfolioResult.cumulative3Y.portfolioSharpeRatio), formatNum(portfolioResult.cumulative3Y.benchmarkSharpeRatio)],
      ['Max Drawdown', formatPct(portfolioResult.cumulative3Y.portfolioMaxDrawdown, 1), formatPct(portfolioResult.cumulative3Y.benchmarkMaxDrawdown, 1)]
    ]
    
    autoTable(doc, {
      startY: yPos,
      head: [[cum3YData[0][0], cum3YData[0][1], cum3YData[0][2]]],
      body: cum3YData.slice(1),
      theme: 'striped',
      styles: {
        fontSize: 9,
        cellPadding: 2
      },
      headStyles: {
        fillColor: [66, 139, 202],
        textColor: [255, 255, 255],
        fontStyle: 'bold'
      },
      columnStyles: {
        0: { cellWidth: 35, fontStyle: 'bold' },
        1: { cellWidth: 35 },
        2: { cellWidth: 35 }
      },
      margin: { left: margin, right: margin }
    })
    
    yPos = doc.lastAutoTable.finalY + 10
  }
  
  // Benchmark note
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(120, 120, 120)
  doc.text(
    'The benchmark used to calculate alpha, beta, capture ratio is: S&P 500 Index TR',
    margin,
    yPos
  )
  
  // Footer on first page(s)
  const footerY = doc.internal.pageSize.getHeight() - 10
  doc.setFontSize(8)
  doc.setTextColor(150, 150, 150)
  doc.text('Clockwise Capital', margin, footerY)
  doc.text(
    `Data: ${portfolioResult.dataStartDate} to ${portfolioResult.dataEndDate}`,
    pageWidth - margin,
    footerY,
    { align: 'right' }
  )
  
  // Add disclosure pages at the end
  addDisclosurePages(doc)
  
  return doc
}

/**
 * Generate comparison PDF with all portfolios
 */
export function generateComparisonPDF(data: MultiPortfolioResult): jsPDF {
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4'
  })
  
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 15
  let yPos = 20
  
  const { comparison } = data
  const portfolioNames = sortPortfolioNames(comparison.portfolioNames)
  const periodNames = comparison.periodNames
  
  // Header
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text('Portfolio Comparison', margin, yPos)
  
  yPos += 8
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 100, 100)
  doc.text(`As of ${data.asOfDate}`, margin, yPos)
  
  yPos += 3
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, margin, yPos)
  
  // For each period
  for (const periodName of periodNames) {
    yPos += 12
    
    // Check if we need a new page
    if (yPos > doc.internal.pageSize.getHeight() - 50) {
      doc.addPage()
      yPos = 20
    }
    
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(0, 0, 0)
    doc.text(periodName, margin, yPos)
    
    yPos += 5
    
    // Build table data
    const tableData: string[][] = []
    const metricsDisplay: Array<[string, string, boolean]> = [
      ['return', 'Return', true],
      ['stdDev', 'Std Dev', true],
      ['alpha', 'Alpha', true],
      ['beta', 'Beta', false],
      ['sharpe', 'Sharpe', false],
      ['maxDrawdown', 'Max Drawdown', true],
      ['upCapture', 'Up Capture', false],
      ['downCapture', 'Down Capture', false]
    ]
    
    for (const [key, label, isPct] of metricsDisplay) {
      const metric = comparison.metrics[key]
      if (!metric) continue
      
      const row = [label]
      for (const portName of portfolioNames) {
        const value = metric.byPeriod[periodName]?.[portName]
        row.push(isPct ? formatPct(value, 1) : formatNum(value))
      }
      // Add benchmark
      const benchValue = metric.benchmark[periodName]
      row.push(isPct ? formatPct(benchValue, 1) : formatNum(benchValue))
      
      tableData.push(row)
    }
    
    // Shorten portfolio names for table headers
    const shortNames = portfolioNames.map(n => n.replace('Clockwise ', ''))
    
    autoTable(doc, {
      startY: yPos,
      head: [['Metric', ...shortNames, 'S&P 500 TR']],
      body: tableData,
      theme: 'striped',
      styles: {
        fontSize: 8,
        cellPadding: 2
      },
      headStyles: {
        fillColor: [66, 139, 202],
        textColor: [255, 255, 255],
        fontStyle: 'bold'
      },
      columnStyles: {
        0: { cellWidth: 35 }
      },
      margin: { left: margin, right: margin }
    })
    
    yPos = doc.lastAutoTable.finalY + 5
  }
  
  // Footer on comparison pages
  const footerY = doc.internal.pageSize.getHeight() - 10
  doc.setFontSize(8)
  doc.setTextColor(150, 150, 150)
  doc.text('Clockwise Capital', margin, footerY)
  doc.text(
    `Data: ${data.dataStartDate} to ${data.dataEndDate}`,
    pageWidth - margin,
    footerY,
    { align: 'right' }
  )
  
  // Add disclosure pages at the end
  addDisclosurePages(doc)
  
  return doc
}

/**
 * Download PDF with given filename
 */
export function downloadPDF(doc: jsPDF, filename: string): void {
  doc.save(filename)
}

/**
 * Generate and download individual portfolio PDF
 */
export function downloadPortfolioPDF(
  data: MultiPortfolioResult,
  portfolioName: string
): void {
  const doc = generatePortfolioPDF(data, portfolioName)
  const safeName = portfolioName.replace(/[^a-zA-Z0-9]/g, '_')
  const dateStr = data.asOfDate.replace(/-/g, '')
  downloadPDF(doc, `${safeName}_Performance_${dateStr}.pdf`)
}

/**
 * Generate and download comparison PDF
 */
export function downloadComparisonPDF(data: MultiPortfolioResult): void {
  const doc = generateComparisonPDF(data)
  const dateStr = data.asOfDate.replace(/-/g, '')
  downloadPDF(doc, `Clockwise_Portfolio_Comparison_${dateStr}.pdf`)
}

